function task = createThermalPipelineTask(scenario, network)
%CREATETHERMALPIPELINETASK One configuration for a complete, auditable run.
if nargin < 1 || isempty(scenario), scenario = leotherm.defaultScenario; end
if nargin < 2 || isempty(network), network = leotherm.defaultReceiverNetwork; end
task = struct('schema', 'leotherm.pipeline_task.v1', ...
    'mode', 'pipeline', 'scenario', scenario, 'network', network, ...
    'surfaceMesh', [], 'volumeMesh', [], 'material', struct, ...
    'couplingOptions', struct, ...
    'geometry', struct('enabled', false, 'solver', 'coupled'), ...
    'sweep', struct('enabled', false, 'mode', 'beta_altitude', ...
        'altitudeKm', [], 'betaDeg', [], 'branch', 1, ...
        'dates', [], 'inclinationDeg', [], 'raanDeg', []), ...
    'telemetry', struct('enabled', false, 'source', [], 'mapping', [], ...
        'options', leotherm.telemetryOptions, 'workflow', 'orbit', ...
        'independentHoldoutConfirmed', false), ...
    'calibration', struct('enabled', false, 'source', [], 'mapping', [], ...
        'profile', [], 'split', table, ...
        'settings', leotherm.deviceCalibrationOptions), ...
    'language', 'zh');
end
