function text = deviceCalibrationText(value, language)
%DEVICECALIBRATIONTEXT Localize report tokens, not stored parameter identifiers.
language = leotherm.normalizeLanguage(language);
codes = ["train","validation","test","exclude", ...
    "physical","effective","unverified", ...
    "capacityJK","internalPowerW","projectedAreaM2","radiatingAreaM2", ...
    "solarAbsorptivity","irEmissivity","conductanceWK", ...
    "accepted_within_declared_scope","review_required","criteria_not_met", ...
    "best_start_not_converged","parameters_near_bounds", ...
    "parameter_stability_not_assessed","near_optimal_parameter_instability", ...
    "training_sensitivity_rank_deficient","weak_parameter_sensitivity", ...
    "effective_parameters_not_component_measurements","holdout_history_not_confirmed", ...
    "forcing_independence_not_confirmed","parameter_evidence_not_confirmed", ...
    "conditioned_on_measured_initial_state","conditional_boundary_driven_validation", ...
    "synthetic_not_flight_validation","rmse_criterion_not_specified","insufficient_dynamic_coverage"];
zh = ["标定","验证","最终检查","排除", ...
    "部件物理参数","模型等效参数","依据未确认", ...
    "热容","内部功耗","投影面积","辐射面积","太阳吸收率","红外发射率","节点间热导", ...
    "在声明范围内满足判据","需要复核","未满足误差判据", ...
    "最优起点未收敛","参数接近边界","多起点稳定性未充分检查","近优参数不稳定", ...
    "标定数据的灵敏度矩阵秩不足","参数对标定数据的影响较弱", ...
    "等效参数不能解释成单个部件的测量值","未确认检查数据的独立使用历史", ...
    "未确认驱动数据独立于目标测温","未确认设备参数依据", ...
    "以每段首个实测温度为条件","以规定热边界为条件的验证", ...
    "合成数据不属于在轨实测验证","未设置温度误差验收上限","有效时长、连续段或温度变化覆盖不足"];
en = ["Calibration","Validation","Final check","Excluded", ...
    "Component physical parameter","Model-effective parameter","Unverified", ...
    "Heat capacity","Internal power","Projected area","Radiating area", ...
    "Solar absorptivity","IR emissivity","Inter-node conductance", ...
    "Meets criteria within declared scope","Review required","Error criteria not met", ...
    "Best start did not converge","Parameters near bounds", ...
    "Multistart stability not assessed","Near-optimal parameter instability", ...
    "Training sensitivity matrix is rank deficient","Weak training sensitivity", ...
    "Effective parameters are not component measurements","Holdout history not confirmed", ...
    "Forcing independence not confirmed","Parameter evidence not confirmed", ...
    "Conditioned on measured initial state","Conditioned on prescribed thermal boundaries", ...
    "Synthetic data are not flight validation","Temperature error criterion not specified", ...
    "Insufficient scored duration, continuity or temperature variation"];
values = en; if strcmp(language,'zh'), values = zh; end
text = string(value);
for k = 1:numel(codes), text(string(value) == codes(k)) = values(k); end
end
