function text = preflightText(codes,language)
%PREFLIGHTTEXT Localized, actionable data-screen findings.
keys=["missing_external_power","incomplete_or_mixed_orbit_mapping","unconfirmed_frame", ...
    "incomplete_attitude","no_contiguous_drivers","exclusion_removes_segments", ...
    "no_measured_temperature","missing_initial_temperature","rejected_driving_rows","structural_checks_passed"];
zh=["热功率模式需要为每个节点映射外部吸收功率，包括明确的零值。", ...
    "轨道模式需要完整的位置、速度和太阳位置，不能同时映射外部热功率。", ...
    "请核对并确认轨道与太阳位置的地心惯性坐标系。", ...
    "姿态旋转矩阵必须映射全部九项，或全部不映射。", ...
    "没有至少两个相邻有效驱动历元的连续段。", ...
    "起始排除时长覆盖所有连续段；请检查数据长度和排除设置。", ...
    "未映射测温：可进行驱动仿真，但无法计算测温误差。", ...
    "启用了实测初温，但部分段首缺少有效测温；请检查首值或关闭该初始化方式。", ...
    "部分驱动记录无效，将断段；不会补齐或插值。", ...
    "映射和驱动结构检查通过；积分是否成功、模型是否合理仍需运行和验证。"];
en=["Heat mode requires absorbed external power for every node, including explicit zeros.", ...
    "Orbit mode requires complete position, velocity and Sun position, without external-power mapping.", ...
    "Verify and confirm the common geocentric inertial frame.", ...
    "Map all nine attitude matrix entries, or none.", ...
    "No segment has at least two adjacent valid driving epochs.", ...
    "Initial exclusion covers every segment. Check record duration and exclusion settings.", ...
    "No measured temperature is mapped. Driving simulation is possible, but temperature errors cannot be scored.", ...
    "Measured initialization is enabled, but some segment starts lack valid temperatures.", ...
    "Some driving records are invalid and will split segments; no filling or interpolation is applied.", ...
    "Mapping and driver structure passed. Solver success and physical agreement still require separate checks."];
labels=en; if strcmp(leotherm.normalizeLanguage(language),'zh'), labels=zh; end
text=string(codes);
for k=1:numel(keys), text(string(codes)==keys(k))=labels(k); end
end
