function writeTelemetrySummary(result, report, data, path, language)
%WRITETELEMETRYSUMMARY Human-readable evidence boundaries and paired errors.
language = leotherm.normalizeLanguage(language);
fid = fopen(path, 'w', 'n', 'UTF-8');
if fid < 0, error('leotherm:TelemetryExport', 'Cannot write the validation summary.'); end
cleanup = onCleanup(@() fclose(fid));
put(fid, pick(language, '# 遥测一致性评估报告', '# Telemetry agreement report'));
put(fid, sprintf(pick(language, '软件版本：%s  ', 'Software version: %s  '), leotherm.version));
put(fid, sprintf(pick(language, '输入数据：`%s`  ', 'Input data: `%s`  '), data.source));
put(fid, sprintf(pick(language, '原始数据行数：%d  ', 'Original data rows: %d  '), height(data.rawTable)));
put(fid, sprintf(pick(language, '每段起始排除时长：%g秒。', 'Excluded initial window per segment: %g s.'), ...
    report.options.excludeInitialS));
if strcmp(report.datasetKind, 'synthetic_demo_not_flight_data')
    put(fid, pick(language, '**这些数据为合成演示数据，不是卫星实测，不能作为独立物理验证证据。**', ...
        '**Synthetic demonstration data, not flight measurements or independent physical validation.**'));
end
if isfield(result, 'provenance')
    if isfield(result.provenance, 'boundaryConditioning') && result.provenance.boundaryConditioning
        put(fid, pick(language, ['本次仿真使用规定的边界温度和导热系数，边界导热为“导热系数乘以边界温度减节点温度”。' ...
            '边界温度不是待验证节点的测温序列，不得把该序列复制为边界输入。' ...
            '结果属于给定边界条件下的节点验证，不代表整星温度或边界自身得到验证。' ...
            '边界输入逐段左端保持；导出的边界热流为采样点瞬时值，正值表示流入节点，不是累计能量。'], ...
            ['Prescribed reservoir temperatures and conductances drive this simulation via G*(T_boundary-T_node). ' ...
            'Do not copy the target temperature series into a boundary channel. Agreement is conditional on these ' ...
            'boundaries, not validation of the whole spacecraft or the boundary temperatures themselves. ' ...
            'Boundary inputs are left-held on valid intervals. Exported heat flow is instantaneous at sample times, ' ...
            'positive into the node, not integrated energy.']));
    end
    put(fid, pick(language, ['遥测仿真未执行周期预热。每个连续有效段独立初始化；坏行和超限间隔断段。' ...
        '仅在有效相邻样本之间，将该区间起点的热功率保持至下一采样时刻，不插值或补齐缺测。'], ...
        ['No periodic warm-up was applied. Each contiguous valid segment was initialized separately. ' ...
        'Rejected rows and excessive intervals break segments. Heat inputs are held at their left sample ' ...
        'within valid intervals only; no missing telemetry is interpolated or filled.']));
    if strcmp(result.provenance.initialization, 'measured_initial_temperature_conditioned')
        put(fid, pick(language, ['初始状态使用了所映射的实测温度，属于条件验证，不是完全独立预测。' ...
            '各段首样本及设置的起始窗口不参与打分，未测节点仍采用网络设定的初温。'], ...
            ['Mapped measured temperatures conditioned the initial state; this is not fully independent prediction. ' ...
            'Each first sample and the configured initial window are excluded. Unmeasured nodes use model initial values.']));
    else
        put(fid, pick(language, '初始温度来自热网络设定；当前流程未根据验证温度调整参数。', ...
            'Initial temperatures came from the network configuration; this workflow did not tune parameters to validation temperatures.'));
    end
    put(fid, sprintf(pick(language, '完整段数：%d；未完成或孤立段数：%d。', ...
        'Complete segments: %d; failed or isolated segments: %d.'), ...
        sum(result.segments.status == "complete"), sum(result.segments.status ~= "complete")));
end
put(fid, pick(language, '## 温度误差', '## Temperature errors'));
put(fid, pick(language, ['仅使用完全相同的协调世界时历元进行配对。残差定义为“仿真减实测”；' ...
    '不拟合偏置、比例或时间偏移。统计按有效样本等权计算，样本数不代表独立重复实验数。'], ...
    ['Only exact UTC matches are paired. Residuals are simulation minus measurement; no offset, gain, ' ...
    'or time shift is fitted. Statistics are sample-weighted; samples are not independent experimental replicates.']));
if isempty(report.metrics)
    put(fid, pick(language, '未映射测温通道，当前结果只属于仿真，无法进行温度验证。', ...
        'No measured-temperature channels were mapped. This is a simulation only, without temperature validation.'));
else
    put(fid, pick(language, '| 节点 | 有效实测数 | 统计配对数 | 平均偏差（K） | 平均绝对误差（K） | 均方根误差（K） | 最大绝对误差（K） |', ...
        '| Node | Valid measurements | Scored pairs | Bias (K) | MAE (K) | RMSE (K) | Max absolute (K) |'));
    put(fid, '|---|---:|---:|---:|---:|---:|---:|');
    names = leotherm.nodeDisplayNames(cellstr(report.metrics.node), language);
    for k = 1:height(report.metrics)
        row = report.metrics(k,:);
        put(fid, sprintf('| %s | %d | %d | %.6g | %.6g | %.6g | %.6g |', ...
            names{k}, row.valid_measured, row.used_samples, row.bias_k, row.mae_k, row.rmse_k, row.max_abs_k));
    end
    put(fid, '');
    if sum(report.metrics.used_samples) == 0
        put(fid, pick(language, '**没有有效配对，不能评价模型与测温数据的一致性。**', ...
            '**No eligible pairs: agreement with the measurements cannot be evaluated.**'));
    end
end
if isfinite(report.options.rmseToleranceK)
    put(fid, sprintf(pick(language, '用户指定的均方根误差上限为%g K；它不是软件内置的物理正确性标准。', ...
        'The user-supplied RMSE limit is %g K; it is not a built-in physical-validity criterion.'), ...
        report.options.rmseToleranceK));
end
put(fid, pick(language, '## 结论边界', '## Interpretation boundary'));
put(fid, pick(language, ['本报告仅评价模型与这些观测的一致性，不能单独证明模型物理正确。' ...
    '正式验证需要确认测温传感器误差、节点位置对应、功率测量含义、姿态和坐标系一致，' ...
    '并使用未参与热参数标定的数据。模型在其他卫星、季节和工况下的适用性仍需独立验证。'], ...
    ['This report assesses agreement with these observations, not proof of physical correctness. ' ...
    'Formal validation requires sensor uncertainty, correct sensor-to-node correspondence, power definitions, ' ...
    'consistent attitude and frames, and data withheld from parameter calibration. Generalization to other ' ...
    'missions, seasons, and operating conditions needs independent evidence.']));
put(fid, pick(language, '逐行采用/拒绝记录、原始输入、列映射、模型参数和完整误差保存在同目录的数据文件中。', ...
    'The accompanying files preserve row dispositions, original input, column mapping, model parameters, and paired errors.'));
end

function put(fid, text)
if startsWith(text, '|')
    fprintf(fid, '%s\n', text);
else
    fprintf(fid, '%s\n\n', text);
end
end

function value = pick(language, chinese, english)
if strcmp(language, 'zh'), value = chinese; else, value = english; end
end
