function generate_paper1_source_data(profile)
%GENERATE_PAPER1_SOURCE_DATA Export representative time series and network data.

if nargin < 1
    profile = 'paper';
end
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(root, 'src'));
config = paper1_config(profile);
outDir = config.outputDirectory;
assert(exist(outDir, 'dir') == 7, ...
    'Run run_paper1_experiments before exporting source data.');
network = leotherm.symmetricReceiverNetwork;

targets = [0, 30, 70];
for index = 1:numel(targets)
    target = targets(index);
    scenario = config.baseScenario;
    scenario.name = sprintf('source_beta_%g', target);
    scenario.orbit.altitudeM = 600e3;
    scenario.orbit.inclinationDeg = 90;
    scenario.orbit.useJ2 = false;
    scenario.environment.freezeSunAtEpoch = true;
    [scenario.orbit.raanDeg, accessible] = leotherm.solveRaanForBeta( ...
        scenario.startEpoch, scenario.orbit.inclinationDeg, target, 1);
    assert(accessible, 'Representative beta angle is inaccessible.');
    result = leotherm.simulateScenario(scenario, network);
    response = network.roles.response;
    source = table(result.timeS, result.timeS / result.orbit.periodS, ...
        result.orbit.betaDeg, result.loads.visibleFraction, ...
        sum(result.loads.directSolarW, 2), sum(result.loads.albedoW, 2), ...
        sum(result.loads.earthIRW, 2), sum(result.loads.totalExternalW, 2), ...
        result.temperatureK(:, 7), result.temperatureK(:, response), ...
        'VariableNames', {'time_s', 'orbit_phase', 'beta_deg', ...
        'solar_visibility', 'direct_solar_w', 'albedo_w', 'earth_ir_w', ...
        'total_absorbed_heat_w', 'structure_temperature_k', ...
        'response_temperature_k'});
    writetable(source, fullfile(outDir, ...
        sprintf('source_figure1_beta_%02d.csv', target)));
end

nodes = table((1:numel(network.nodeNames))', network.nodeNames', ...
    network.capacityJK, network.internalPowerW, network.projectedAreaM2, ...
    network.radiatingAreaM2, network.solarAbsorptivity, network.irEmissivity, ...
    'VariableNames', {'node_index', 'node_name', 'capacity_j_k', ...
    'internal_power_w', 'projected_area_m2', 'radiating_area_m2', ...
    'solar_absorptivity', 'ir_emissivity'});
writetable(nodes, fullfile(outDir, 'source_network_nodes.csv'));

[left, right] = find(triu(network.conductanceWK, 1) > 0);
conductance = network.conductanceWK(sub2ind(size(network.conductanceWK), left, right));
edges = table(left, right, network.nodeNames(left)', network.nodeNames(right)', ...
    conductance, 'VariableNames', {'source_index', 'target_index', ...
    'source_node', 'target_node', 'conductance_w_k'});
writetable(edges, fullfile(outDir, 'source_network_conductance.csv'));
end
