function outputPath = run_generic_exchange_adapter(outputDirectory)
%RUN_GENERIC_EXCHANGE_ADAPTER Run the dependency-free adapter demonstration.
%   The values are synthetic bookkeeping fixtures. They are not a thermal
%   correlation, a solver benchmark, or spacecraft data.

root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(root, 'src'));
if nargin < 1 || isempty(outputDirectory)
    outputDirectory = tempname;
    mkdir(outputDirectory);
elseif ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

units = struct('length','m','mass','kg','time','s','temperature','K', ...
    'power','W','heatCapacity','J/K','conductance','W/K','area','m^2');
source = struct('modelId','generic_adapter_fixture', ...
    'createdUTC','2026-01-01T00:00:00Z', 'units', units, ...
    'description','Synthetic neutral record; not spacecraft data.');
source = struct('schema','leotherm.thermal_model.v1', ...
    'metadata',source, ...
    'nodes',struct('id',{'n1','n2'},'name',{'structure','payload'}, ...
        'positionM',{[0 0 0],[0.1 0 0]}, ...
        'capacityJK',{1000,250},'initialTemperatureK',{293.15,293.15}, ...
        'internalPowerW',{0,1}), ...
    'materials',struct('id','fixture_material','name','Synthetic reference', ...
        'conductivityWmK',10,'densityKgM3',1000,'specificHeatJkgK',1000, ...
        'source','fixture only','confidence','low','uncertainty',struct('relative',0.5)), ...
    'components',struct('id','payload_component','name','Payload', ...
        'nodeIds',{{'n2'}},'capacityJK',250,'internalPowerW',1, ...
        'source','fixture only','confidence','low','uncertainty',struct), ...
    'contacts',struct('id','fixture_contact','nodeIds',{{'n1','n2'}}, ...
        'conductanceWK',0.5), ...
    'boundaries',struct([]), ...
    'provenance',struct('source','generic adapter synthetic fixture', ...
        'status','unverified_fixture','transformations',{{'none'}}), ...
    'uncertainty',struct('enabled',false,'source','fixture only'));

outputPath = fullfile(outputDirectory, 'generic_exchange_model.json');
[~, report] = generic_exchange_adapter(source, outputPath);
fprintf('Generic exchange adapter wrote %s (%s).\n', report.outputPath, report.schema);
end
