function report = verify_v014_release
%VERIFY_V014_RELEASE Run the v0.14 exchange regression gate and static scan.
% The gate intentionally excludes GUI and production solver execution.
root = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(root, 'src'));
testFile = fullfile(root, 'tests', 'test_v014_release_regression.m');
results = runtests(testFile);
failed = [results.Failed];
incomplete = [results.Incomplete];

files = {fullfile(root, 'tests', 'test_v014_release_regression.m'), ...
    fullfile(root, 'tools', 'verify_v014_release.m'), ...
    fullfile(root, 'src', '+leotherm', 'componentModel.m'), ...
    fullfile(root, 'src', '+leotherm', '+io', 'importThermalModel.m'), ...
    fullfile(root, 'src', '+leotherm', '+io', 'exportThermalModel.m'), ...
    fullfile(root, 'src', '+leotherm', '+model', 'previewNetworkMapping.m'), ...
    fullfile(root, 'src', '+leotherm', '+model', 'applyNetworkMapping.m'), ...
    fullfile(root, 'src', '+leotherm', '+model', 'validateNetworkMapping.m'), ...
    fullfile(root, 'src', '+leotherm', '+model', 'sampleUncertainty.m'), ...
    fullfile(root, 'src', '+leotherm', 'materialLibrary.m')};
static = repmat(struct('file', '', 'messages', []), numel(files), 1);
for k = 1:numel(files)
    static(k).file = files{k};
    static(k).messages = checkcode(files{k}, '-id');
end

report = struct('tests', results, 'failed', sum(failed), ...
    'incomplete', sum(incomplete), 'static', static, ...
    'matlabRelease', version('-release'));
fprintf('V014_TEST_FAILED=%d V014_TEST_INCOMPLETE=%d MATLAB=%s\n', ...
    report.failed, report.incomplete, report.matlabRelease);
assert(report.failed == 0, 'v0.14 exchange regression failed.');
end
